---
name: one
on:
  pull_request:
    branches:
      - main

jobs:
  one:
    timeout-minutes: 120
    name: one
    runs-on: ubuntu-latest
    steps:
      # List 5 kubernetes ingress-nginx repository's releases between release "NGINX: 0.44.0" and release "NGINX: 0.44.0"
      # excluding precised ranges and by matching regex_filter value and ignoring from_release parameter value
      - uses: github-actions-tools/gh-list-releases@main
        id: list-releases
        with:
          owner: kubernetes
          repo: ingress-nginx
          from_release: "NGINX: 0.44.0"
          to_release: "NGINX: 0.45.0"
          nb_results: 10
          exclude_ranges: |
            -3
            5
            7-8
            9-
          regex_filter: "/^(?!helm-chart-3.25.0|helm-chart-3.27.0).*/i"
          skip_from_release: true

      - run: |
          echo '${{ steps.list-releases.outputs.releases }}' | jq -r '.[]' | while read release ; do 
            echo "release: ${release}"
          done
