---
name: one
on:
  issue_comment:
    types: [created]

jobs:
  one:
    if: contains(github.event.comment.html_url, '/pull/') && github.event.comment.body == 'TF apply'
    timeout-minutes: 120
    name: one
    runs-on: ubuntu-latest
    steps:
      - uses: github-actions-tools/gh-reviews-count@main
        id: reviewsCount
        with:
          pull_request: $${{ github.event.issue.number }}

      - run: echo "The approved reviews count is ${REVIEWS}"
        if: success() && steps.reviewsCount.outputs.approved
        env:
          REVIEWS: ${{ steps.reviewsCount.outputs.approved }}

      - uses: actions/github-script@v3
        with:
          script: |
            const output = `#### approved : ${{ steps.reviewsCount.outputs.approved }}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
